curl -X POST --data "first_name=first&last_name=last&email=test@email.com&password=password" http://127.0.0.1:9000/api/v1/user/register
token="$(curl -X POST --data "username=test@email.com&password=password" http://127.0.0.1:9000/api/v1/login/ | python3 -c "import sys, json; print(json.load(sys.stdin)['token'])")"
curl -X POST --data "first_name=first&last_name=last&email=test2@email.com&password=password" http://127.0.0.1:9000/api/v1/user/register
token2="$(curl -X POST --data "username=test2@email.com&password=password" http://127.0.0.1:9000/api/v1/login/ | python3 -c "import sys, json; print(json.load(sys.stdin)['token'])")"
echo "Getting details on book 1"
curl -X GET http://127.0.0.1:9000/api/v1/book/1 -H "Authorization: JWT $token"
echo "\nIncrementing the number of reads on book 1"
curl -X POST http://127.0.0.1:9000/api/v1/inc_book_reads/1 -H "Authorization: JWT $token"
echo "\nGetting details on book 1"
curl -X GET http://127.0.0.1:9000/api/v1/book/1 -H "Authorization: JWT $token"
echo "\nCreating a review of book 1"
curl -X POST -d '{"book":1, "rating": 5, "review": "good vibes"}'  http://127.0.0.1:9000/api/v1/create_or_edit_review -H "Authorization: JWT $token" -H "Content-Type: application/json"
echo "\nCreating a review of book 1 by another user"
curl -X POST -d '{"book":1, "rating": 1, "review": "bad vibes"}'  http://127.0.0.1:9000/api/v1/create_or_edit_review -H "Authorization: JWT $token2" -H "Content-Type: application/json"
echo "\nGetting the details of the second user's reivew of book 1"
curl -X GET http://127.0.0.1:9000/api/v1/view_review/1/2 -H "Authorization: JWT $token"
echo "\nGetting the currently authenticated user's reivew of book 1"
curl -X GET http://127.0.0.1:9000/api/v1/view_review/1 -H "Authorization: JWT $token"
echo "\nGetting all the reviews of book 1"
curl -X GET http://127.0.0.1:9000/api/v1/get_all_book_reviews/1 -H "Authorization: JWT $token"
echo "\nDelete the authenticated users's review of book 1"
curl -X POST -d '{"book":1}'  http://127.0.0.1:9000/api/v1/delete_review -H "Authorization: JWT $token" -H "Content-Type: application/json"
echo "\nDelete the authenticated users's review of book 1"
curl -X POST -d '{"book":1}'  http://127.0.0.1:9000/api/v1/delete_review -H "Authorization: JWT $token" -H "Content-Type: application/json"
echo "\nGetting the details of the second user's reivew of book 1"
curl -X GET http://127.0.0.1:9000/api/v1/view_review/1/2 -H "Authorization: JWT $token"
echo "\nGetting all the reviews of book 1"
curl -X GET http://127.0.0.1:9000/api/v1/get_all_book_reviews/1 -H "Authorization: JWT $token"