# Generated by Django 3.0.7 on 2020-07-02 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_readbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
