# Generated by Django 3.0.7 on 2020-07-14 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_readbook_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.Book')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_for', to='api.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
