# Generated by Django 3.0.7 on 2020-07-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recommendation'),
        ('api', '0007_challenge'),
    ]

    operations = [
    ]
