# Generated by Django 3.0.7 on 2020-07-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='total_ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
